aplicaciones/adopcion/urls.py
from django.conf.urls import url
from aplicaciones.adopcion.views import index_adopcion, SolicitudList, SolicitudCreate, solicitud_listar, \
    solicitud_crear

urlpatterns = [
url(r'^solicitud/class/listar$', SolicitudList.as_view(), name='solicitud_listar'),
url(r'^solicitud/class/crear$', SolicitudCreate.as_view(), name='solicitud_crear'),
url(r'^solicitud/funcion/listar$', solicitud_listar, name='solicitud_listarFuncion'),
url(r'^solicitud/funcion/crear$', solicitud_crear, name='solicitud_crearFuncion'),

]

refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('aplicaciones.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('aplicaciones.adopcion.urls', namespace="adopcion")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

aplicaciones/adopcion/models.py
# -*- coding: utf-8 -*-
#from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Persona(models.Model):
    nombre = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=70)
    edad = models.IntegerField()
    telefono = models.CharField(max_length=12)
    email = models.EmailField()
    domicilio = models.TextField()

    def __unicode__(self):
        return '{} {}'.format(self.nombre, self.apellidos)

class Solicitud(models.Model):
    persona = models.ForeignKey(Persona, null=True, blank=True)
    numero_mascotas = models.IntegerField()
    razones = models.TextField()

aplicaciones/adopcion/forms.py
from django import forms
from django.forms import widgets
from aplicaciones.adopcion.models import Persona, Solicitud

class PersonaForm(forms.ModelForm):
    
    class Meta: 
        model = Persona
        fields = [
            'nombre',
            'apellidos',
            'edad',
            'telefono',
            'email',
            'domicilio'
        ]
        labels = {
            'nombre': 'Nombre',
            'apellidos': 'Apellidos',
            'edad': 'Edad',
            'telefono': 'Telefono',
            'email': 'Email',
            'domicilio': 'Domicilio'
        }
        widgets = {
            'nombre':forms.TextInput(attrs={'class': 'form-control'}),
            'apellidos':forms.TextInput(attrs={'class': 'form-control'}),
            'edad':forms.TextInput(attrs={'class': 'form-control'}),
            'telefono':forms.TextInput(attrs={'class': 'form-control'}),
            'email':forms.TextInput(attrs={'class': 'form-control'}),
            'domicilio:':forms.Textarea(attrs={'class': 'form-control'})
        }

class SolicitudForm(forms.ModelForm):

    class Meta:
        model = Solicitud
        fields = [
            'numero_mascotas',
            'razones'
        ]
        labels = {
            'numero_mascotas': 'Numero de mascotas',
            'razones': 'Razones'
        }
        widgets = {
            'numero_mascotas': forms.TextInput(attrs={'class': 'form-control'}),
            'razones': forms.Textarea(attrs={'class': 'form-control'})
        }

aplicaciones/adopcion/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponseRedirect

from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from django.shortcuts import redirect, render, render_to_response
from django.http import HttpResponse
from django.urls import reverse_lazy
# Create your views here.

# Importar modelos
from aplicaciones.adopcion.models import Solicitud, Persona

# Importar forms
from aplicaciones.adopcion.forms import PersonaForm, SolicitudForm

def index_adopcion(request):
    return HttpResponse("Index Adopcion") 

def solicitud_listar(request):
    solicitud = Solicitud.objects.all()
    contexto = {"solicitudes": solicitud}
    return render(request, 'adopcion/solicitud_list_fun.html', contexto)

def solicitud_crear(request):
    form = SolicitudForm()
    form2 = PersonaForm()

    if request.method == "POST":
        form = SolicitudForm(request.POST)
        form2 = PersonaForm(request.POST)

        if form.is_valid() and form2.is_valid():
            solicitud = form.save(commit = False)
            solicitud.persona = form2.save()
            solicitud.save()
        return redirect('adopcion:solicitud_listarFuncion')
    context = { "form": form, "form2": form2 }
    return render(request, 'adopcion/solicitud_form.html', context=context)

class SolicitudList(ListView):
    model = Solicitud
    template_name = 'adopcion/solicitud_list.html'

class SolicitudCreate(CreateView):
    model = Solicitud
    template_name = 'adopcion/solicitud_form.html'
    form_class = SolicitudForm
    second_form_class = PersonaForm
    success_url = reverse_lazy('adopcion:solicitud_listar')

    def get_context_data(self, **kwargs ):
        contexto = super(SolicitudCreate, self).get_context_data(**kwargs)
        if 'form' not in contexto:
            contexto['form'] = self.form_class(self.request.GET)
        if 'form2' not in contexto:
            contexto['form2'] = self.second_form_class(self.request.GET)  
        return contexto

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form2 = self.second_form_class(request.POST)
        if form.is_valid() and form2.is_valid():
            solicitud = form.save(commit = False)
            solicitud.persona = form2.save()
            solicitud.save()
            return HttpResponseRedirect(self.get_success_url())
        else: 
            return self.render_to_response(self.get_context_data(form=form, form2=form2))

templates/adopcion/solicitud_form.html
{% extends 'base/base.html' %}

{% block header %}
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {{ form2.as_p }}

    <button type="submit">Guardar</button>
</form>
{% endblock %}

templates/adopcion/solicitud_list.html
{% extends 'base/base.html' %}

{% block title %}
Clases
{% endblock %}

{% block header %}
<h2>App Mascotas - Usando Clases</h2>
{% endblock %}

{% block content %}

<table class="table table-bordered">
<thead>
    <tr>
        <td>No. Solicitud</td>
        <td>Adoptante</td>
        <td>No. Mascotas</td>
        <td>Razones</td>
        <td>Acciones</td>
    </tr>

</thead>
<tbody>
    {% if object_list %}
    {% for solicitud in object_list %}
    <tr>
        <td>{{ solicitud.id }}</td>
        <td>{{ solicitud.persona.nombre }} {{ solicitud.persona.apellidos }}</td>
        <td>{{ solicitud.numero_mascotas }}</td>
        <td>{{ solicitud.razones }}</td>

        <td>
            <a class="btn btn-primary" href="#">Editar</a>
            <a class="btn btn-danger" href="#">Eliminar</a>
        </td>
    </tr>
    {% endfor %}
    {% else %}
    <h1>No hay registros</h1>
    {% endif %}
</tbody>
</table>
<a class="btn btn-primary" href="{% url 'adopcion:solicitud_crear' %}">Agregar nuevo</a>
{% endblock %}

{% block footer %}
{% endblock %}

templates/adopcion/solicitud_list_fun.html
{% extends 'base/base.html' %}

{% block title %}
Funciones
{% endblock %}

{% block header %}
<h2>App Mascotas - Usando Funciones</h2>
{% endblock %}

{% block content %}

<table class="table table-bordered">
<thead>
    <tr>
        <td>No. Solicitud</td>
        <td>Adoptante</td>
        <td>No. Mascotas</td>
        <td>Razones</td>
        <td>Acciones</td>
    </tr>

</thead>
<tbody>
    {% if solicitudes %}
    {% for solicitud in solicitudes %}
    <tr>
        <td>{{ solicitud.id }}</td>
        <td>{{ solicitud.persona.nombre }} {{ solicitud.persona.apellidos }}</td>
        <td>{{ solicitud.numero_mascotas }}</td>
        <td>{{ solicitud.razones }}</td>

        <td>
            <a class="btn btn-primary" href="#">Editar</a>
            <a class="btn btn-danger" href="#">Eliminar</a>
        </td>
    </tr>
    {% endfor %}
    {% else %}
    <h1>No hay registros</h1>
    {% endif %}
</tbody>
</table>
<a class="btn btn-primary" href="{% url 'adopcion:solicitud_crearFuncion' %}">Agregar nuevo</a>
{% endblock %}

{% block footer %}
{% endblock %}