aplicaciones/mascota/urls.py
from django.conf.urls import url, include

from aplicaciones.mascota.views import index, mascota_create, mascota_list, mascota_edit, mascota_delete, \
    MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^funcion/nuevo$', mascota_create , name= 'mascota_crearFunction'),
    url(r'^funcion/listar$', mascota_list, name= 'mascota_listarFunction'),
    url(r'^funcion/editar/(?P<id_mascota>\d+)/$', mascota_edit, name= 'mascota_editarFunction'),
    url(r'^funcion/eliminar/(?P<id_mascota>\d+)/$', mascota_delete, name= 'mascota_eliminarFunction'),
    url(r'^clase/nuevo$', MascotaCreate.as_view() , name= 'mascota_crear'),
    url(r'^clase/listar$', MascotaList.as_view(), name= 'mascota_listar'),
    url(r'^clase/editar/(?P<pk>\d+)/$', MascotaUpdate.as_view(), name= 'mascota_editar'),
    url(r'^clase/eliminar/(?P<pk>\d+)/$', MascotaDelete.as_view(), name= 'mascota_eliminar'),

]

refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('aplicaciones.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('aplicaciones.adopcion.urls', namespace="adopcion")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block extrastatic %}
    {% endblock %}

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <title>{% block title %}Base {% endblock %}</title>
</head>
<body>
{% block header %}
{% include 'base/header.html' %}
{% endblock %}

{% block content %} 
<h5>Este es el contenido del archivo base</h5>
{% endblock %}

{% block footer %}
<h4></h4>
{% endblock %}


<script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>

templates/base/header.html
<h1>App Mascotas</h1>

templates/base/index.html
{% extends 'base/base.html' %}

{% block title %}
App Mascota
{% endblock %}

{% block content %}
<div>
    <a class="btn btn-primary" href="{% url 'mascota:mascota_listarFunction' %}">Formulario Funtion-Based Views</a>
    <a class="btn btn-primary" href="{% url 'mascota:mascota_listar' %}">Formulario Class-Based Views</a>
</div>
{% endblock %}

{% block footer %}
{% endblock %}