aplicaciones/adopcion/urls.py
from django.conf.urls import url
from aplicaciones.adopcion.views import index_adopcion, SolicitudList, SolicitudCreate, solicitud_listar, \
    solicitud_crear

urlpatterns = [
url(r'^solicitud/class/listar$', SolicitudList.as_view(), name='solicitud_listar'),
url(r'^solicitud/class/crear$', SolicitudCreate.as_view(), name='solicitud_crear'),
url(r'^solicitud/funcion/listar$', solicitud_listar, name='solicitud_listarFuncion'),
url(r'^solicitud/funcion/crear$', solicitud_crear, name='solicitud_crearFuncion'),

]

aplicaciones/mascota/urls.py
from django.conf.urls import url, include

from aplicaciones.mascota.views import index, mascota_create, mascota_list, mascota_edit, mascota_delete, \
    MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^funcion/nuevo$', mascota_create , name= 'mascota_crearFunction'),
    url(r'^funcion/listar$', mascota_list, name= 'mascota_listarFunction'),
    url(r'^funcion/editar/(?P<id_mascota>\d+)/$', mascota_edit, name= 'mascota_editarFunction'),
    url(r'^funcion/eliminar/(?P<id_mascota>\d+)/$', mascota_delete, name= 'mascota_eliminarFunction'),
    url(r'^clase/nuevo$', MascotaCreate.as_view() , name= 'mascota_crear'),
    url(r'^clase/listar$', MascotaList.as_view(), name= 'mascota_listar'),
    url(r'^clase/editar/(?P<pk>\d+)/$', MascotaUpdate.as_view(), name= 'mascota_editar'),
    url(r'^clase/eliminar/(?P<pk>\d+)/$', MascotaDelete.as_view(), name= 'mascota_eliminar'),

]

refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('aplicaciones.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('aplicaciones.adopcion.urls', namespace="adopcion")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

aplicaciones/mascota/models.py
# -*- coding: utf-8 -*-
#from __future__ import unicode_literals

from django.db import models

from aplicaciones.adopcion.models import Persona

# Create your models here.

class Vacuna (models.Model):
    nombre= models.CharField(max_length=50)

    def __unicode__(self):
        return '{}'.format(self.nombre)

class Mascota(models.Model): 
    nombre = models.CharField(max_length=50)
    sexo = models.CharField(max_length=10)
    edad_aprox = models.IntegerField()
    fecha_rescate = models.DateField()
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE) 
    vacuna = models.ManyToManyField(Vacuna, blank=True)
    imagen = models.ImageField(upload_to="mascotas", null=True)

aplicaciones/mascota/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from aplicaciones.mascota.models import Mascota


class MascotaForm(forms.ModelForm):
    
    class Meta:
        model = Mascota

        fields = [
            'nombre',
            'sexo',
            'edad_aprox',
            'fecha_rescate',
            'persona',
            'vacuna',
            'imagen'
        ]
        labels = {
            'nombre': 'Nombre',
            'sexo': 'Sexo',
            'edad_aprox': 'Edad aproximada',
            'fecha_rescate': 'Fecha de rescate (YYYY-MM-DD)',
            'persona': 'Adoptante',
            'vacuna': 'Vacunas',
            'imagen': 'Fotografía'
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'sexo': forms.TextInput(attrs={'class': 'form-control'}),
            'edad_aprox': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_rescate': forms.TextInput(attrs={'class': 'form-control'}),
            'persona': forms.Select(attrs={'class': 'form-control'}),
            'vacuna': forms.CheckboxSelectMultiple(),
            
        }

aplicaciones/mascota/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import reset_queries

from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.utils.translation import templatize
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from aplicaciones.mascota.forms import MascotaForm
from aplicaciones.mascota.models import Mascota
# Create your views here.

def index(request):
    return render(request, 'mascota/index.html')


def mascota_create(request):
    if request.method == 'POST':
        form = MascotaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_listarFunction')
    else:
        form = MascotaForm()
    return render(request, 'mascota/mascota_form.html', {'form': form})

def mascota_list(request):
    mascota = Mascota.objects.all().order_by('id')
    contexto = {'mascotas': mascota}
    return render(request, 'mascota/mascota_list_fun.html', contexto)

def mascota_edit(request, id_mascota):
    mascota = Mascota.objects.get(id = id_mascota)
    if request.method == 'GET':
        form = MascotaForm(instance=mascota)
    else: 
        form = MascotaForm(request.POST, instance=mascota)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_listarFunction')
    return render(request, 'mascota/mascota_form.html', {'form': form})

def mascota_delete(request, id_mascota):
    mascota = Mascota.objects.get(id = id_mascota)
    if request.method == 'POST':
        mascota.delete()
        return redirect('mascota:mascota_listarFunction')
    return render(request, 'mascota/mascota_delete_fun.html', {'mascota': mascota})

class MascotaList(ListView):
    model = Mascota
    template_name = 'mascota/mascota_list.html'

class MascotaCreate(CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar' )

class MascotaUpdate(UpdateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar' )

class MascotaDelete(DeleteView):
    model = Mascota
    template_name = 'mascota/mascota_delete.html'
    success_url = reverse_lazy('mascota:mascota_listar')

templates/mascota/index.html
{% extends 'base/base.html' %}

{% block title %}
App Mascota
{% endblock %}

{% block content %}
<h3>Mascotas</h3>
<div>
    <a class="btn btn-primary" href="{% url 'mascota:mascota_listarFunction' %}">Formulario Funtion-Based Views</a>
    <a class="btn btn-primary" href="{% url 'mascota:mascota_listar' %}">Formulario Class-Based Views</a>
</div>
<h3>Solicitudes</h3>
<div>
    <a class="btn btn-primary" href="{% url 'adopcion:solicitud_listarFuncion' %}">Formulario Funtion-Based Views</a>
    <a class="btn btn-primary" href="{% url 'adopcion:solicitud_listar' %}">Formulario Class-Based Views</a>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

templates/mascota/mascota_delete.html
{% extends 'base/base.html' %}

{% block title %}
Clases
{% endblock %}

{% block header %}
<h2>App Mascotas - Usando Clases</h2>
{% endblock %}

{% block content %}
<form method="POST" enctype="multipart/form-data">

    <!-- Eltoken siempre debe ir  -->
    {% csrf_token %}
    <h2>¿Desea eliminar el registro de {{ object.nombre }} ?</h2>

<button class="btn btn-danger" type="submit" >Sí, eliminar</button>
<a class="btn btn-default" href="{% url 'mascota:mascota_listar'  %}">Cancelar</a>
</form>
{% endblock %}

templates/mascota/mascota_delete_fun.html
{% extends 'base/base.html' %}

{% block title %}
Funciones
{% endblock %}

{% block header %}
<h2>App Mascotas - Usando Funciones</h2>
{% endblock %}

{% block content %}
<form method="POST" enctype="multipart/form-data">

    <!-- Eltoken siempre debe ir  -->
    {% csrf_token %}
    <h2>¿Desea eliminar el registro de {{ mascota.nombre }} ?</h2>

<button class="btn btn-danger" type="submit" >Sí, eliminar</button>
<a class="btn btn-default" href="{% url 'mascota:mascota_listar'  %}">Cancelar</a>
</form>
{% endblock %}

templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar">
</form>
{% endblock %}

templates/mascota/mascota_list.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}
Clases
{% endblock %}

{% block header %}
<h2>App Mascotas - Usando Clases</h2>
{% endblock %}

{% block content %}
<table class="table table-bordered">
    <thead>
        <tr>
            <td>#</td>
            <td>Nombre</td>
            <td>Sexo</td>
            <td>Edad</td>
            <td>Fecha de Rescate</td>
            <td>Adoptante</td>
            <td>Fotografía</td>
            <td>Acciones</td>
        </tr>
    </thead>
    <tbody>
        {% if object_list %}
        {% for mascota in object_list %}

        <tr>
            <td>{{ mascota.id }}</td>
            <td>{{ mascota.nombre }}</td>
            <td>{{ mascota.sexo }}</td>
            <td>{{ mascota.edad_aprox }}</td>
            <td>{{ mascota.fecha_rescate }}</td>
            <td>{{ mascota.persona.nombre}} {{ mascota.persona.apellidos }}</td>
            {% if mascota.imagen %}
                <td><img src="{{ mascota.imagen.url }}" alt="Imagen perrito" width="120px" height="100px"></td>
            {% else %}
                <td><img src="{% static 'img/obito.png' %}" alt="Imagen perrito" width="120px" height="100px"></td>
            {% endif %}
            <td><a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
            <a class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a></td>
        </tr>
        {% endfor %}
        {% else %}
        <h1>No hay registros</h1>
        {% endif %}
    </tbody>
</table>

<a class="btn btn-primary" href="{% url 'mascota:mascota_crear' %}">Agregar nuevo</a>




{% endblock %}}

{% block footer %}
{% endblock %}

templates/mascota/mascota_list_fun.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block title %}
Funciones
{% endblock %}

{% block header %}
<h2>App Mascotas - Usando Funciones</h2>
{% endblock %}

{% block content %}
<table class="table table-bordered">
    <thead>
        <tr>
            <td>#</td>
            <td>Nombre</td>
            <td>Sexo</td>
            <td>Edad</td>
            <td>Fecha de Rescate</td>
            <td>Adoptante</td>
            <td>Fotografía</td>
            <td>Acciones</td>
        </tr>
    </thead>
    <tbody>
        {% if mascotas %}
        {% for mascota in mascotas %}

        <tr>
            <td>{{ mascota.id }}</td>
            <td>{{ mascota.nombre }}</td>
            <td>{{ mascota.sexo }}</td>
            <td>{{ mascota.edad_aprox }}</td>
            <td>{{ mascota.fecha_rescate }}</td>
            <td>{{ mascota.persona.nombre}} {{ mascota.persona.apellidos }}</td>
            {% if mascota.imagen %}
            <td><img src="{{ mascota.imagen.url }}" alt="Imagen perrito" width="120px" height="100px"></td>
            {% else %}
            <td><img src="{% static 'img/obito.png' %}" alt="Imagen perrito" width="120px" height="100px"></td>
            {% endif %}
            <td><a class="btn btn-primary" href="{% url 'mascota:mascota_editarFunction' mascota.id %}">Editar</a>
            <a class="btn btn-danger" href="{% url 'mascota:mascota_eliminarFunction' mascota.id %}">Eliminar</a></td>
        </tr>
        {% endfor %}
        {% else %}
        <h1>No hay registros</h1>
        {% endif %}
    </tbody>
</table>

<a class="btn btn-primary" href="{% url 'mascota:mascota_crearFunction' %}">Agregar nuevo</a>




{% endblock %}}

{% block footer %}
{% endblock %}